name: CD

on:
  push:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-22.04

      permissions:
        contents: read
        packages: write

      steps:
      - uses: actions/checkout@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: ./build.sh
      - name: Test
        run: wasm-pack test --chrome --firefox --headless
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm pack && npm publish
        working-directory: ./pkg
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#      - run: npm login --scope=@brief-jetzt --registry=https://npm.pkg.github.com --always-auth
#      - run: wasm-pack publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}