name: CD

on:
  push:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build
        run: ./build.sh
      - name: Test
        run: wasm-pack test --chrome --firefox --headless
      - name: Publish
        run: wasm-pack publish