name: CI

on:
  pull_request:
  push:

jobs:
  shellcheck:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Install shellcheck
      run: sudo apt-get install -y shellcheck
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        check_together: 'yes'