name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-node@v7
        with:
          node-version: latest
          cache: npm
      - run: npm ci
      - run: node --run ci
      - run: node --run test
