name: CI

on:
  pull_request:
  push:

jobs:
  shellcheck:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: shellcheck ./**/*.sh
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        check_together: 'yes'

  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - run: ./build.sh
    - run: cargo test
    - run: wasm-pack test --chrome --firefox --headless
